---
title: "Main"
author: "Tan Hao Qin"
date: "2 August 2016"
output: pdf_document
---

```{r setup, include=FALSE, error=TRUE}
knitr::opts_chunk$set(echo = TRUE)
library('mlogit')
```

## Read data, always do this


```{r read cars}
train <- read.csv('train.csv')
test <- read.csv('test.csv')
test2 <- read.csv('test.csv')
submission <- read.csv('samplesubmission.csv')
str(train)
str(test)
summary(train)
summary(test)
```

```{r format test data}
test$income <- lapply(test$income, as.character)
test$income <- factor(test$income,levels=levels(train$income))

Test <- mlogit.data(test, shape = 'wide', choice = "Choice", varying = c(4:83), sep = '', alt.levels = c("Ch1", "Ch2", "Ch3", "Ch4"), id.var = "Case")
Test$Ch1 = 0
Test$Ch2 = 0
Test$Ch3 = 0
Test$Ch4 = 0
Test$Choice = FALSE
```


```{r format train data with factors to numbers}
train2 <- read.csv('train.csv')
summary(train2)
str(train2)

#change gender, male = 1, female = 0
train2$gender <- ifelse(train2$gender == 'Male', 1, 0)


#change miles to avg of range, except over 400 which becomes 500
train2$miles <- factor(train2$miles, levels = c("Under 50 Miles","51 To 100 Miles","101 To 150 Miles","151 To 200 Miles","201 To 250 Miles","251 To 300 Miles","301 To 350 Miles","351 To 400 Miles","Over 400 Miles"))
table(train2$miles)
train2$miles <- (as.numeric(train2$miles)-1)*50 + 25
table(train2$miles)
train2$miles <- ifelse(train2$miles == 425, 500, train2$miles)
table(train2$miles)

#change night percentage to average of range
train2$night<- factor(train2$night, levels = c("Under 10%","10% To 20%","21% To 30%", "31% To 40%", "41% To 50%","51% To 60%","61% To 70%", "71% To 80%","81% To 90%","91% To 100%" ))
table(train2$night)
train2$night <- (as.numeric(train2$night)-1)*10+5
table(train2$night)

#change age to average of age, except over 60 changed to 70
train2$age <- factor(train2$age, levels = c("Under 30", "30 To 39", "40 To 49", "50 To 59", "60 & Over"))
table(train2$age)
train2$age <- (as.numeric(train2$age)-1)*10+25
train2$age <- ifelse(train2$age==65, 70, train2$age)

str(train2)


#change urbanisation, with Rural/Country = 0, Suburban = 1, Urban/City = 2
train2$Urb <- ifelse(train2$Urb=="Rural/Country", 0, ifelse(train2$Urb=="Suburban", 1, ifelse(train2$Urb=="Urban/City", 2, train2$Urb)))
str(train2$Urb)
str(train2)


#change education, Grade School = 0, High School = 1, Trade/Vocational School = 2, Some College (1-3 Years) = 3, College Graduate (4 Years) = 4, Postgraduate College = 5

train2$educ <- as.character(train2$educ)

ifelse(train2$educ=="Grade School", 0, ifelse(train2$educ=="High School", 1, ifelse(train2$educ=="Trade/Vocational School", 2, ifelse(train2$educ=="Some College (1-3 Years)", 3, ifelse(train2$educ=="College Graduate (4 Years)", 4, ifelse(train2$educ=="Postgraduate College", 5, train2$educ))))))

train2$educ <- as.numeric(train$educ)
str(train2$educ)

str(train2)

# change income to average of range
summary(train2$income)

train2$income <- factor(train2$income, levels = c("Under $29,999", "$30,000 to $39,999", "$40,000 to $49,999", "$50,000 to $59,999", "$60,000 to $69,999", "$70,000 to $79,999", "$80,000 to $89,999", "$90,000 to $99,999","$100,000 to $109,999", "$110,000 to $119,999", "$120,000 to $129,999", "$130,000 to $139,999", "$140,000 to $149,999", "$150,000 to $159,999", "$160,000 to $169,999", "$170,000 to $179,999", "$180,000 to $189,999", "$190,000 to $199,999", "$200,000 to $209,999", "$210,000 to $219,999", "$220,000 to $229,999","$230,000 to $239,999", "$240,000 to $249,999", "$250,000 to $259,999", "$260,000 to $269,999", "$270,000 to $279,999", "$280,000 to 2$89,999", "$290,000 to $299,999", "$300,000 & Over"))

table(train2$income)
train2$income <- (as.numeric(train$income)-1)*10000+25000
train2$income <- ifelse(train2$income==25000, 20000, ifelse(train2$income==245000, 250000, train2$income))

str(train2)

#change parking frequency to number of times per year
summary(train2$ppark)
head(train2$ppark)

train2$ppark <- as.character(train2$ppark)
train2$ppark <- factor(train2$ppark, levels = c("Never", "Yearly", "Monthly", "Weekly",  "Daily"))
train2$ppark <- ifelse(train2$ppark == "Never", 0, ifelse(train2$ppark =="Yearly", 1, ifelse(train2$ppark == "Monthly", 12,ifelse(train2$ppark == "Weekly", 52, ifelse(train2$ppark == "Daily", 365, train2$ppark)))))

summary(train2$ppark)

#ignore region, segment of car

```

```{r format test with numbers for factors}
test2$income <- lapply(test2$income, as.character)
test2$income <- factor(test2$income, levels=levels(train$income))

#change gender, male = 1, female = 0
test2$gender <- ifelse(test2$gender == 'Male', 1, 0)


#change miles to avg of range, except over 400 which becomes 500
test2$miles <- factor(test2$miles, levels = c("Under 50 Miles","51 To 100 Miles","101 To 150 Miles","151 To 200 Miles","201 To 250 Miles","251 To 300 Miles","301 To 350 Miles","351 To 400 Miles","Over 400 Miles"))
table(test2$miles)
test2$miles <- (as.numeric(test2$miles)-1)*50 + 25
table(test2$miles)
test2$miles <- ifelse(test2$miles == 425, 500, test2$miles)
table(test2$miles)

#change night percentage to average of range
test2$night<- factor(test2$night, levels = c("Under 10%","10% To 20%","21% To 30%", "31% To 40%", "41% To 50%","51% To 60%","61% To 70%", "71% To 80%","81% To 90%","91% To 100%" ))
table(test2$night)
test2$night <- (as.numeric(test2$night)-1)*10+5
table(test2$night)

#change age to average of age, except over 60 changed to 70
test2$age <- factor(test2$age, levels = c("Under 30", "30 To 39", "40 To 49", "50 To 59", "60 & Over"))
table(test2$age)
test2$age <- (as.numeric(test2$age)-1)*10+25
test2$age <- ifelse(test2$age==65, 70, test2$age)

str(test2)

#change urbanisation, with Rural/Country = 0, Suburban = 1, Urban/City = 2
test2$Urb <- ifelse(test2$Urb=="Rural/Country", 0, ifelse(test2$Urb=="Suburban", 1, ifelse(test2$Urb=="Urban/City", 2, test2$Urb)))
str(test2$Urb)
str(test2)

test2 <- mlogit.data(test2, shape = 'wide', choice = "Choice", varying = c(4:83), sep = '', alt.levels = c("Ch1", "Ch2", "Ch3", "Ch4"), id.var = "Case")
test2$Ch1 = 0
test2$Ch2 = 0
test2$Ch3 = 0
test2$Ch4 = 0
test2$Choice = FALSE
```

Tasks <= 12 are in D and tasks > 12 are in V
shape is wide because 4 choices are in the same row
```{r seperate train data for testing}
A <- mlogit.data(train, shape = 'wide', choice = "Choice", varying = c(4:83), sep = '', alt.levels = c("Ch1", "Ch2", "Ch3", "Ch4"), id.var = "Case")

D <- mlogit.data(subset(train, Task <= 12), shape = 'wide', choice = "Choice", varying = c(4:83), sep = '', alt.levels = c("Ch1", "Ch2", "Ch3", "Ch4"), id.var = "Case")

V <- mlogit.data(subset(train, Task > 12), shape = 'wide', choice = "Choice", varying = c(4:83), sep = '', alt.levels = c("Ch1", "Ch2", "Ch3", "Ch4"), id.var = "Case")
ActualChoice <- subset(train, Task > 12)[,"Choice"]
```

```{r seperate train2 data for testing with converted factors}
A2 <- mlogit.data(train2, shape = 'wide', choice = "Choice", varying = c(4:83), sep = '', alt.levels = c("Ch1", "Ch2", "Ch3", "Ch4"), id.var = "Case")

D2 <- mlogit.data(subset(train2, Task <= 12), shape = 'wide', choice = "Choice", varying = c(4:83), sep = '', alt.levels = c("Ch1", "Ch2", "Ch3", "Ch4"), id.var = "Case")

V2 <- mlogit.data(subset(train2, Task > 12), shape = 'wide', choice = "Choice", varying = c(4:83), sep = '', alt.levels = c("Ch1", "Ch2", "Ch3", "Ch4"), id.var = "Case")
ActualChoice2 <- subset(train2, Task > 12)[,"Choice"]
```

##Simple models
```{r model1 mlogit}
model1 <- mlogit(Choice~CC+GN+NS+BU+FA+LD+BZ+FC+FP+RP+PP+KA+SC+TS+NV+MA+LB+AF+HU+Price-1, data = D)
summary(model1)

model3star <- mlogit(Choice~CC+BU+KA+SC+TS+MA+Price-1, data = D)
summary(model3star)

model2star <- mlogit(Choice~CC+BU+KA+SC+TS+MA+GN+LD+Price-1, data = D)
summary(model2star)

model1star <- mlogit(Choice~CC+BU+KA+SC+TS+MA+GN+LD+NS+BZ+RP+LB+HU+Price-1, data = D)
summary(model1star)
```

```{r validate}
predict1 <- predict(model1, newdata = V)
predict3star <- predict(model3star, newdata = V)
predict2star <- predict(model2star, newdata = V)
predict1star <- predict(model1star, newdata = V)

PredictChoice1 <- apply(predict1, 1, which.max)
PredictChoice3star <- apply(predict3star, 1, which.max)
PredictChoice2star <- apply(predict2star, 1, which.max)
PredictChoice1star <- apply(predict1star, 1, which.max)

t1 <- table(ActualChoice, PredictChoice1)
t3s <- table(ActualChoice, PredictChoice3star)
t2s <- table(ActualChoice, PredictChoice2star)
t1s <- table(ActualChoice, PredictChoice1star)

choiceVector <- vector(mode = "list", length = 4)
choiceVector[[1]] <- t1
choiceVector[[2]] <- t3s
choiceVector[[3]] <- t2s
choiceVector[[4]] <- t1s
```

model 1 with all variables is best
```{r compare accuracy}
accurate_cnt <- c()
for(i in 1:4){
  accurate_cnt <- c(accurate_cnt, 0)
  for(j in 1:4){
    accurate_cnt[i] <- accurate_cnt[i] + choiceVector[[i]][j,j]
  }
}
accurate_cnt
```



```{r pred1 mlogit all variables D data}
TestPredict <- predict(model1, newdata = Test)
Submission1 <- submission
for (i in 1:length(TestPredict)){
  for (j in colnames(TestPredict)){
    Submission1[i,j] = TestPredict[i,j]
  }
}
write.csv(Submission1, file = 'Submission1.csv')
```

```{r pred3 2nd best mlogit with 1star variables}
TestPredict <- predict(model1star, newdata = Test)
Submission3 <- submission
for (i in 1:length(TestPredict)){
  for (j in colnames(TestPredict)){
    Submission3[i,j] = TestPredict[i,j]
  }
}
write.csv(Submission3, file = 'Submission3.csv')
```

```{r model2 random parameters}
model2 <- mlogit(Choice~CC+GN+NS+BU+FA+LD+BZ+FC+FP+RP+PP+KA+SC+TS+NV+MA+LB+AF+HU+Price-1, data = D, rpar = c(CC = 'n',  GN = 'n',  NS = 'n',  BU = 'n',  FA = 'n',  LD = 'n',  BZ = 'n',  FC = 'n',  FP = 'n',  RP = 'n',  PP = 'n',  KA = 'n',  SC = 'n',  TS = 'n',  NV = 'n',  MA = 'n',  LB = 'n',  AF = 'n',  HU = 'n', Price = 'n'), panel = TRUE, print.level = TRUE)
summary(model2)
```

```{r pred2 random parameter}
Pred2 <- predict(model2, newdata = Test)
Submission2 <- submission
for (i in 1:length(Pred2)){
  for (j in colnames(Pred2)){
    Submission2[i,j] = Pred2[i,j]
  }
}
write.csv(Submission2, file = 'Submission2.csv')
```



```{r pred4 mlogit with A data}
A <- mlogit.data(train, shape = 'wide', choice = "Choice", varying = c(4:83), sep = '', alt.levels = c("Ch1", "Ch2", "Ch3", "Ch4"), id.var = "Case")

model1A <- mlogit(Choice~CC+GN+NS+BU+FA+LD+BZ+FC+FP+RP+PP+KA+SC+TS+NV+MA+LB+AF+HU+Price-1, data = A)
summary(model1A)

Pred1A <- predict(model1A, newdata = Test)
Submission4 <- submission
for (i in 1:nrow(Pred1A)){
  for (j in colnames(Pred1A)){
    Submission4[i,j] = Pred1A[i,j]
  }
}
write.csv(Submission4, file = 'Submission4.csv')
```

```{r pred5&6 mlogit with numerical factor data}

A <- mlogit.data(train, shape = 'wide', choice = "Choice", varying = c(c(4:83)), sep = '', alt.levels = c("Ch1", "Ch2", "Ch3", "Ch4"), id.var = "Case")

model1A <- mlogit(Choice~CC+GN+NS+BU+FA+LD+BZ+FC+FP+RP+PP+KA+SC+TS+NV+MA+LB+AF+HU+Price-1 | gender+miles+night+age+Urb, data = A)
summary(model1A)

Pred1A <- predict(model1A, newdata = Test)
Submission6 <- submission
for (i in 1:nrow(Pred1A)){
  for (j in colnames(Pred1A)){
    Submission6[i,j] = Pred1A[i,j]
  }
}
write.csv(Submission6, file = 'Submission6.csv')

```

```{r model 7 with all factors}
model7_pre <- mlogit(Choice~CC+GN+NS+BU+FA+LD+BZ+FC+FP+RP+PP+KA+SC+TS+NV+MA+LB+AF+HU+Price -1| gender+miles+night+age+Urb, data = D2)
summary(model7_pre)


model7 <- mlogit(Choice~CC+GN+NS+BU+FA+LD+BZ+FC+FP+RP+PP+KA+SC+TS+NV+MA+LB+AF+HU+Price -1| gender+miles+night+age+Urb+educ+income+ppark, data = D2)
summary(model7)

model7_3star <- mlogit(Choice~GN+NS+BU+FA+LD+BZ+FC+FP+RP+PP+KA+SC+TS+NV+MA+LB+AF+HU+Price-1 | age+Urb, data = D2)
summary(model7_3star)

model7_2star <- mlogit(Choice~GN+NS+BU+FA+LD+BZ+FC+FP+RP+PP+KA+SC+TS+NV+MA+LB+AF+HU+Price-1 | age+Urb+ppark, data = D2)
summary(model7_2star)

model7_1star <- mlogit(Choice~GN+NS+BU+FA+LD+BZ+FC+FP+RP+PP+KA+SC+TS+NV+MA+LB+AF+HU+Price-1 | miles+age+Urb+educ+ppark, data = D2)
summary(model7_1star)

Pred7_pre <- predict(model7_pre, newdata = V2)
Pred7 <- predict(model7, newdata = V2)
Pred7_3star <- predict(model7_3star, newdata = V2)
Pred7_2star <- predict(model7_2star, newdata = V2)
Pred7_1star <- predict(model7_1star, newdata = V2)
```

```{r validate model7}
PredictChoice7_pre <- apply(Pred7_pre, 1, which.max)
PredictChoice7 <- apply(Pred7, 1, which.max)
PredictChoice7_3star <- apply(Pred7_3star, 1, which.max)
PredictChoice7_2star <- apply(Pred7_2star, 1, which.max)
PredictChoice7_1star <- apply(Pred7_1star, 1, which.max)


t1_pre <- table(ActualChoice2, PredictChoice7_pre)
t1 <- table(ActualChoice2, PredictChoice7)
t3s <- table(ActualChoice2, PredictChoice7_3star)
t2s <- table(ActualChoice2, PredictChoice7_2star)
t1s <- table(ActualChoice2, PredictChoice7_1star)


choiceVector <- vector(mode = "list", length = 5)
choiceVector[[1]] <- t1_pre
choiceVector[[2]] <- t1
choiceVector[[3]] <- t3s
choiceVector[[4]] <- t2s
choiceVector[[5]] <- t1s

```

```{r compare accuracy}
accurate_cnt <- c()
for(i in 1:5){
  accurate_cnt <- c(accurate_cnt, 0)
  for(j in 1:4){
    accurate_cnt[i] <- accurate_cnt[i] + choiceVector[[i]][j,j]
  }
}
accurate_cnt/4550
```
all variables without educ, income, ppark: 51.4%
all variables: 50.989%
3 star variables: 50.791%
2 star variables: 50.989%
1 star variables: 50.83%

```{r pred 7 submission}
#write file
Submission6 <- submission
for (i in 1:nrow(Pred1A)){
  for (j in colnames(Pred1A)){
    Submission6[i,j] = Pred1A[i,j]
  }
}
write.csv(Submission6, file = 'Submission6.csv')

```



##CART

```{r cart}
library(rpart)
library(rpart.plot)

train_split =read.csv("output.csv")

cart1 = rpart(Choice~CC1+GN1+NS1+BU1+FA1+LD1+BZ1+FC1+FP1+RP1+PP1+KA1+SC1+TS1+NV1+MA1+LB1+AF1+HU1+Price1+CC2+GN2+NS2+BU2+FA2+LD2+BZ2+FC2+FP2+RP2+PP2+KA2+SC2+TS2+NV2+MA2+LB2+AF2+HU2+Price2+CC3+GN3+NS3+BU3+FA3+LD3+BZ3+FC3+FP3+RP3+PP3+KA3+SC3+TS3+NV3+MA3+LB3+AF3+HU3+Price3+CC4+GN4+NS4+BU4+FA4+LD4+BZ4+FC4+FP4+RP4+PP4+KA4+SC4+TS4+NV4+MA4+LB4+AF4+HU4+Price4,data=train,method = "class") 
cart2 = rpart(Choice~CC+GN+NS+BU+FA+LD+BZ+FC+FP+RP+PP+KA+SC+TS+NV+MA+LB+AF+HU+Price,data=train_split,method="class") 

prp(cart1)
prp(cart2)
```

```{r}

```

